### ISSUE TITLE
CSS.escape not always exposed in WebKit Nightly

### ISSUE THREAD

**Issue by rodneyrehm** [mathiasbynens/CSS.escape#2]
It seems that an internal optimization / bug in WebKit/JavaScriptCore can cause `CSS.escape === undefined` even though the polyfill is properly loaded and executed.

This can be observed in Safari on El Capitan an [WebKit Nightly](http://nightly.webkit.org/). The behavior is *not* reproducible consistently. On my system it always occured on cold cache and every 3rd or 4th reload. 

If you add `console.log(CSS.escape)` right after the polyfill's function expression, the function is always available globally. The same is true for explicitly assigning the function to the global space using `root._css_escape_webkit_fun = CSS.escape = function(value){ … }`. This leads me to believe some optimization heuristic is going haywire.

I'm aware this is *not* a problem of *this* project, yet this is the first - and only - situation I've seen this happen. I have not opened a WebKit bug for this, mostly because I don't even know the terms to search for existing reports…

**Comment by mathiasbynens** [comment]
Do you have a test case I can use to try to reproduce this?

Can you report this on https://bugs.webkit.org/ anyway? The team will triage it, don’t worry.

**Comment by rodneyrehm** [comment]
sure! [testcase](http://rodneyrehm.de/t/css.escape) and [WebKit issue 149175](https://bugs.webkit.org/show_bug.cgi?id=149175)

**Comment by mathiasbynens** [comment]
Closing in favor of the WebKit bug ticket. Thanks!
