### ISSUE TITLE
CSS.escape undefined in Safari

### ISSUE THREAD

**Issue by gbalkumar** [mathiasbynens/CSS.escape#6]
I upgraded my code to use the latest release v1.5.0 which includes the workaround (as part of #3 ) for the polyfill failure on Webkit. Unfortunately the workaround does not work in the latest version and the issue is still reproducible on Safari Version 9.0.3 (11601.4.4).

[Link](https://www.ganeshbk.com/css-escape/test.html) to test Case

Steps to reproduce - Visit the above link on Safari and use Developer Tools to inspect CSS.escape
Expected result - CSS.escape should be valid and defined consistently.
Actual result - CSS.escape is undefined sometimes.

**Comment by mathiasbynens** [comment]
Here’s the WebKit bug report: https://bugs.webkit.org/show_bug.cgi?id=149175

Can you reproduce this on the latest Safari Technology Preview?

**Comment by mmariano** [comment]
This issue is also happening on iOS.

**Comment by mathiasbynens** [comment]
Happy to, once it’s clear how to work around the WebKit/JavaScriptCore bug.

**Comment by mathiasbynens** [comment]
Closing this issue as it’s been fixed in WebKit/JavaScriptCore and no one has come up with a workaround for the affected versions.
