### ISSUE TITLE
How do I use CSS.escape in a React application?

### ISSUE THREAD

**Issue by maecapozzi** [mathiasbynens/CSS.escape#9]
When I run my tests (written in Jests), I see the warning:  `Warning: [JSS] CSS.escape polyfill in DEV mode is required in this browser, check out https://github.com/mathiasbynens/CSS.escape` . 

I have read the available documentation. I've `npm install`ed it, and tried importing it into my file. 
I tried just importing it like so: 

`import 'css.escape'`

and like so: 

`import cssEscape from 'css.escape'`

 but am not sure where to go from there. 
 

Would you mind explaining to me what I'm missing? Thank you!

```
import React from 'react'
import injectSheet from 'react-jss'
import 'css.escape'

const styles = {
  loginContainer: {
    alignItems: 'center',
    display: 'flex',
    justifyContent: 'center',
    marginTop: '2em',
    textAlign: 'center'
  },
  loginButton: {
    backgroundColor: '#00C457',
    border: 'none',
    fontSize: '1em',
    height: '4em',
    width: '20em',
    margin: '2em'
  },
  buttonLink: {
    color: 'white',
    fontFamily: 'Roboto',
    textDecoration: 'none'
  }
}

const LoginButton = ({ classes, url }) => {
  return (
    <div className={classes.loginContainer}>
      <button className={classes.loginButton}>
        <a className={classes.buttonLink} href={`${url}/auth/spotify`}>Login with Spotify</a>
      </button>
    </div>
  )
}

export default injectSheet(styles)(LoginButton)
```

**Comment by tomershvueli** [comment]
@maecapozzi were you able to get this working? Do you mind documenting how?

**Comment by oktapodia** [comment]
I've manage to get it working with the following

Install it via `npm install` or `yarn install`

And then in your React component, you can do 
```js
import React from 'react'
import CSSEscape from 'css.escape'

class Test extends React.Component {
  render() {
    const cssToEscape = CSSEscape('#form[email]')
    //...
  }
}

```
